const mongoose = require("mongoose");
const validator = require("validator");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");

const userSchema = new mongoose.Schema({
  // IMPORTANT - We dont want multiple users with the same email account
  // So we will use mongoose's "unique" ppt to get this done
  email: {
    type: String,
    unique: true,
    required: false,
    validate(value) {
      if (!validator.isEmail(value)) {
        throw new Error("Email is invalid");
      }
    },
    trim: true,
    lowercase: true,
  },
  password: {
    type: String,
    required: true,
    trim: true,
    minlength: 7,
    validate(value) {
      if (value.toLowerCase().includes("password")) {
        throw new Error("Invalid Password Entered");
      }
    },
  },
  name: {
    type: String,
    required: true,
    trim: true,
  },
  age: {
    type: Number,
    validate(value) {
      if (value < 0) {
        throw new Error("Age should be positive");
      }
    },
    default: 0,
  },
  // tokens is an array of objects
  // Such objects are called sub-documents
  // All documents and their sub-documents have their own _id field, automatically generated by mongo.
  tokens: [
    {
      token: {
        type: String,
        required: true,
      },
    },
  ],
});

// Adding an instance method
// IMP - isko bhi normal function ki tarah hi define karna padega due to the "this" keyword.
userSchema.methods.generateAuthToken = async function () {
  const user = this;

  const token = await jwt.sign({ _id: user._id.toString() }, "iamvengeance", {
    expiresIn: "7 days",
  });

  // adding the token to the user instance
  user.tokens = user.tokens.concat({ token });
  // saving the user instance with the new token value
  await user.save();

  return token;
};

// Adding a static method (model method) to the User schema
// Model methods mai "this" ki baat hi ni hui to no need for normal function
// arrow function will work
userSchema.statics.findByCredentials = async (email, password) => {
  const user = await User.findOne({ email });

  if (!user) {
    throw new Error("Unable to login");
  }

  const isMatch = await bcrypt.compare(password, user.password);

  if (!isMatch) {
    throw new Error("Unable to login");
  }

  return user;
};

// IMPORTANT - Yaha "this" binding ka imp use he, to normal function hi declare karna padega.
// Arrow function won't do the job.
userSchema.pre("save", async function (next) {
  // our user object is stored in "this"
  const user = this;

  // hash the password only if it was modified
  if (user.isModified("password")) {
    user.password = await bcrypt.hash(user.password, 8);
  }

  // call next when we are done with our middleware's body
  next();
});

const User = mongoose.model("User", userSchema);

module.exports = User;
